# Generated by Django 2.2.7 on 2023-05-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('authname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
                ('timestamp', models.TimeField()),
            ],
        ),
    ]
